### ISSUE TITLE
Check documentation for EXPORTNC

### ISSUE THREAD

**Issue by SofianeB** [OphidiaBigData/ophidia-analytics-framework#32]
Here http://ophidia.cmcc.it/documentation/users/operators/OPH_EXPORTNC.html the default value of export_metadata is "yes" but if I don't add this to oph_exportnc, metadata will not be available.

**Comment by eldoo** [comment]
Thanks for reporting this. This was an issue related to PyOphidia where the default value for the 'export_metadata' argument of exportnc/exportnc2 methods was set to "no". This has been fixed in the release v1.6.0 of PyOphidia.
