### ISSUE TITLE
Ophidia analytics fails with error: undefined symbol: oph_pid_drop_session_prefix

### ISSUE THREAD

**Issue by waltersf** [OphidiaBigData/ophidia-analytics-framework#4]
After compiling Ophidia Analytics in Ubuntu and have run run a simple oph_list command in Ophidia Term, an error `undefined symbol: oph_pid_drop_session_prefix` occurs. 

I had to examine slurm job outputs to find the message: 
`symbol lookup error: /usr/local/ophidia/oph-cluster/oph-analytics-framework/lib/drivers/liboph_listoperator.so: undefined symbol: oph_pid_drop_session_prefix`

Possible solution:

In Ubuntu, running the command: `nm --demangle /usr/local/ophidia/oph-cluster/oph-analytics-framework/lib/drivers/liboph_listoperator.so` shows that `oph_pid_drop_session_prefix` was undefined. 
To fix it, I changed:

`BASIC_LIB = -L.. -loph_task_parser -loph_idstring -loph_json`
to 
`BASIC_LIB = -L.. -loph_task_parser -loph_idstring -loph_json -loph_pid`
in file `src/drivers/Makefile.am`.

**Comment by eldoo** [comment]
Thanks for reporting this. The issue has been solved.
