### ISSUE TITLE
export_array not working due to exceeding maxvalue

### ISSUE THREAD

**Issue by SofianeB** [OphidiaBigData/ophidia-analytics-framework#62]
Hi, 
 we encoutered this issue some months ago and the solution was to modify the Ophidia (operator) source code
``` OPH_EXPLORECUBE_operator_1.0.xml.``` and extend the ```maxvalue``` to ```20000```.

We have another use case and the same issue happened. 
From an end-user perspective, Is there a way to handle this problem without going through the source code?

**Comment by eldoo** [comment]
Fixed by #96
